### PR TITLE
fix search error, when adult files showed

### PR DESCRIPTION
**Pull request by czPechy**
When an adult file appeared between the results, there was an error. Modified to view non-adult. May be added in the future to whether adult files should be displayed or not.

### CODE REVIEW

**Comment by czPechy** [comment]
For example, when searching for the word "sex," an older version will display an error. Now a blank list appears because adult files are filtered

**Comment by czPechy** [comment]
But I thought that adult files should be displayed as well. Apparently I was wrong somewhere.

**Comment by czPechy** [comment]
Adult content settings

**Comment by lzoubek** [comment]
cool feature

**Pull request merged**
